Repository Kakao-Groomton-MusicGen/AI-Model, pull requests merged in 2024-09, with the labels that each got.

#8 5-feat-initial-configuration-settingUpload an initial file
  .gitignore
  __pycache__/lyrics_generator.cpython-312.pyc
  __pycache__/openai_client.cpython-312.pyc
  lyrics_generator.py
  main.py
  openai_client.py
  requirements.txt
Labels: feat

#9 7-feat ai-music-model modularization
  gen_music.py
  requirements.txt
Labels: feat

#13 11-refactor modify prompt content
  lyrics_generator.py
  main.py
  openai_client.py
Labels: refactoring

#15 가사 생성 flask 연결
  .gitignore
  app.py
  lyrics_generator.py
  openai_client.py
Labels: feat

#19 16-feat-song-download-link 노래 다운로드 기능 구현, 단 현재 로컬 디렉토리에 저장되게 구성
  .env
  AI-Model/music_output/1fadfb9f-890d-423a-95e1-68430b233a4c.mp3
  AI-Model/music_output/5178d918-47f8-41a5-b5f5-7b82502cfec7.mp3
  __pycache__/audio_client.cpython-312.pyc
  __pycache__/lyrics_generator.cpython-312.pyc
  __pycache__/openai_client.cpython-312.pyc
  app.py
  audio_client.py
  main.py
  music_output/0eed3817-d116-417a-800e-5af2fe691aca.mp3
  music_output/3e28521b-e536-4e60-8cfa-c2a7d15abe59.mp3
  music_output/3fdf6759-0b56-45f1-bf51-a620e97af7d7.mp3
  music_output/4564eaf9-296f-4f94-9914-e2bf8bc7835d.mp3
  music_output/7215bfbc-ca23-405c-80ea-5cf5bddf5e05.mp3
  music_output/9371fbd7-d1ea-4c21-b960-8e4fd51b47e1.mp3
  music_output/95544e95-7577-497e-bd68-d286131ca1cb.mp3
  music_output/af5bbf11-2039-4d11-80b2-6a8f810ddc45.mp3
  music_output/ca0f5373-8d60-47af-878c-0881977883d0.mp3
  music_output/fe0614f6-49d1-400e-9603-6aac7838ae6b.mp3
Labels: feat

#18 17 feat 파라미터 tag 번역 기능 추가
  app.py
  lyrics_generator.py
  openai_client.py
Labels: feat

#21 번역 System Prompt 수정
  openai_client.py
Labels: refactoring

#23 음악 url 2개로 변경
  audio_client.py
  main.py
Labels: bug

#25 음악 업로드 flask 연결
  .env
  app.py
  music_uploader.py
  requirements.txt
Labels: feat

#27 tag에 children song 고정
  lyrics_generator.py
Labels: refactoring
